version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
    ports:
      - "3014:3014"
    links:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: passwordrm
      MYSQL_DATABASE: root
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: "yarn run start"
    volumes:
      - ./client:/app/client
    ports:
      - "3814:3814"
volumes:
  mysql-data:
    driver: local
